import PrintMachine from "./PrintMachine.js";
import News from "./News.js";
import NewsFeed from "./NewsFeed.js";
const machine = new PrintMachine("16px", "green", "sans-serif");
machine.print("Первая задача");
const today = new Date();
const twoDaysAgo = new Date();
twoDaysAgo.setDate(today.getDate() - 2);
const news1 = new News("Первая новость", "Текст один", ["тег"], twoDaysAgo);
const news2 = new News("Вторая новость", "Текст два", ["тег"], today);
const feed = new NewsFeed();
feed.addNews(news1);
feed.addNews(news2);
const element = document.querySelector("#name");
const cl = (text) => {
    element.innerText += text;
};
cl(`Всего новостей: ${feed.getCount()}\n\n`);
feed.sortByDate();
cl("Лента новостей\n");
feed.printAll(cl);
